name: Energylandia Queue Scraper

on:
  schedule:
    - cron: '*/5 7-18 * * *'  # Co 5 minut od 7:00 do 18:55 UTC (czyli 9:00-20:55 CEST)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run queue script
        run: python queue_script.py

      - name: Commit CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add energylandia_queues.csv
          git commit -m "Update queue data [skip ci]" || echo "No changes to commit"
          git push